linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec
    - bodyclose
    - gocritic
    - revive

linters-settings:
  gocyclo:
    min-complexity: 15
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - dist

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0